# dapr/components/pubsub.yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis-pubsub
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: "localhost:6379"
  - name: redisPassword
    secretKeyRef:
      name: redis-secret
      key: password
  - name: enableTLS
    value: "false"
  - name: consumerID
    value: "todo-backend-{podName}"  # Unique per instance
  - name: processingTimeout
    value: "60s"
  - name: redeliverInterval
    value: "30s"
  - name: queueDepth
    value: "100"
  - name: concurrency
    value: "10"