# dapr/components/statestore.yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis-state
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: "localhost:6379"
  - name: redisPassword
    secretKeyRef:
      name: redis-secret
      key: password
  - name: enableTLS
    value: "false"
  - name: maxRetries
    value: "3"
  - name: maxRetryBackoff
    value: "2s"
  # Performance tuning
  - name: queryIndexes
    value: |
      {
        "indexes": [
          {
            "name": "user_id",
            "type": "TEXT"
          },
          {
            "name": "created_at",
            "type": "NUMERIC"
          },
          {
            "name": "priority",
            "type": "TEXT"
          },
          {
            "name": "completed",
            "type": "TEXT"
          }
        ]
      }