#!/usr/bin/env python3
"""Todo Application - Phase I: In-Memory Console App

This application demonstrates spec-driven development using Claude Code and Spec-Kit Plus.
All code generated via AI following specification-first methodology.

Features:
- Add tasks with title and description
- View all tasks with status indicators
- Mark tasks complete/incomplete
- Update task details
- Delete tasks

Constraints:
- In-memory storage only (data not persisted)
- Python 3.13+ standard library only
- No external dependencies
- Clean architecture (domain, service, CLI layers)

Target Audience: Hackathon judges and developers evaluating spec-driven AI implementation

Generated via Claude Code following The Evolution of Todo Constitution.
"""

from src.cli.todo_cli import TodoCLI


def main() -> None:
    """Application entry point.

    Displays welcome message and starts the CLI application loop.
    """
    print("\n" + "=" * 60)
    print("=== Todo Application - Phase I ===")
    print("=== Spec-Driven Development Demo ===")
    print("=" * 60)
    print("\nWARNING: In-memory storage (tasks not persisted after exit)")
    print("INFO: All code generated by Claude Code via specifications\n")

    try:
        cli = TodoCLI()
        cli.run()
    except KeyboardInterrupt:
        print("\n\nApplication interrupted. Goodbye!")
    except Exception as e:
        print(f"\n\n✗ Unexpected error: {e}")
        print("Please report this issue.")


if __name__ == "__main__":
    main()
