apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  - name: vaultName
    value: "taskai-secrets"
  - name: defaultNamespace
    value: "taskai"
scopes:
- backend-api
- recurring-service
- notification-service
