apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    value: "host=localhost user=postgres password=postgres port=5432 dbname=taskai sslmode=disable"
  - name: tableName
    value: "dapr_state"
  - name: metadataTableName
    value: "dapr_metadata"
  - name: timeoutInSeconds
    value: "30"
scopes:
- backend-api
- recurring-service
- notification-service
